import EventDetails from '@/component/EventDetails/EventDetails'
import Head from 'next/head'
import React from 'react'
import HomeNavbar from '@/component/Home/Navbar/Navbar'
import { getEventById } from '@/services/eventService'

const  id = ({eventData}:any) => {

  return (
    <>
    <Head>
      <title>event-details</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomeNavbar />
    <EventDetails eventData={eventData} />
  </>
  )
}

export default id

export const getServerSideProps: any = async (context: any) => {
  
  const event:any = await getEventById(context?.query?.id)

  return {
    props: {
    eventData:event?.data || {}
      
    },
  };
};