
import Head from 'next/head'
import React from 'react'
import HomeNavbar from '@/component/Home/Navbar/Navbar'
import ShopDetails from '@/component/ShopDetails/ShopDetails'

const  id = () => {
  return (
    <>
    <Head>
      <title>event-details</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomeNavbar />
    <ShopDetails/>
  </>
  )
}

export default id