import Head from 'next/head'
import React ,{useContext,useEffect} from 'react'
import HomeNavbar from '@/component/Home/Navbar/Navbar'
import styles from '../styles/checkout.module.scss'
import OrderSummary from '@/component/Common/OrderSummary/OrderSummary'
import UserContext from '@/context/UserContext'
import Button from '@/component/Common/Button/Button'
import { useRouter } from 'next/router'
import { Toaster } from 'react-hot-toast'

const Checkout = () => {
  const router = useRouter()
  const {BookingPayLoad,createBooking,setBookingPayLoad,BookingDetails,createEventBooking}:any=useContext(UserContext);
  
const handleNotes = (e:any) => {
  setBookingPayLoad({...BookingPayLoad,["note"]:e.target.value})
}
console.log(BookingDetails)

useEffect(()=>{
 if(!Object.keys(BookingPayLoad).length){
  router.push('/')
 }

},[])

  const week =['sunday','monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', ]
  const month =['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec' ]
  return (
    <>
          <Head>
        <title>event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <HomeNavbar/>
     <div className={`${styles["checkout-wrapper"]} padding-2rem`}>
<div className={styles["left"]}>
<div className={styles["shop-info"]}> 
        <h1> {BookingDetails?.businessName}</h1>
    <div className={styles["icon-section"]}>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none">
<circle opacity="0.25" cx="12" cy="12" r="10" fill="#EB5757"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M12 6C12.5523 6 13 6.44772 13 7V11.5858L15.2071 13.7929C15.5976 14.1834 15.5976 14.8166 15.2071 15.2071C14.8166 15.5976 14.1834 15.5976 13.7929 15.2071L11.2929 12.7071C11.1054 12.5196 11 12.2652 11 12V7C11 6.44772 11.4477 6 12 6Z" fill="#EB5757"/>
</svg>
    <p>{new Date(BookingPayLoad?.booking_date).getDate()} {month[new Date(BookingPayLoad?.booking_date).getMonth()]}  at {new Date(BookingPayLoad?.booking_time).getHours()}:00</p>

    </div>
    <div className={styles["icon-section"]}>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none">
<path d="M17 6C17 8.76142 14.7614 11 12 11C9.23858 11 7 8.76142 7 6C7 3.23858 9.23858 1 12 1C14.7614 1 17 3.23858 17 6Z" fill="#EB5757"/>
<path opacity="0.25" fill-rule="evenodd" clip-rule="evenodd" d="M18.818 14.1313C18.2016 13.4166 17.1428 13.4534 16.3149 13.9066C15.0338 14.6078 13.5635 15.0064 12 15.0064C10.4365 15.0064 8.96618 14.6078 7.68505 13.9066C6.85717 13.4534 5.79841 13.4166 5.182 14.1313C3.82222 15.7078 3 17.7611 3 20.0064V21.0064C3 22.111 3.89543 23.0064 5 23.0064H19C20.1046 23.0064 21 22.111 21 21.0064V20.0064C21 17.7611 20.1778 15.7078 18.818 14.1313Z" fill="#EB5757"/>
</svg>
    <p>Number of guest : {BookingPayLoad?.total_seats}</p>

    </div>
    <div className={styles["icon-section"]}>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none">
<path opacity="0.25" d="M21 10C21 15.4917 16.1746 20.1791 13.5904 22.2957C12.6534 23.0631 11.3466 23.0631 10.4096 22.2957C7.82537 20.1791 3 15.4917 3 10C3 5.02944 7.02944 1 12 1C16.9706 1 21 5.02944 21 10Z" fill="#EB5757"/>
<path d="M15 9C15 10.6569 13.6569 12 12 12C10.3431 12 9 10.6569 9 9C9 7.34315 10.3431 6 12 6C13.6569 6 15 7.34315 15 9Z" fill="#EB5757"/>
</svg>
    <p>gurgaon haryana 
      <br/> <span>cyber hub dlf phase 4 near ambiance mall</span> </p>

    </div>
    <div className={styles["icon-section"]}>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none">
<path d="M3.69845 15.8112L2.16138 19.91C1.7092 21.1158 2.88673 22.2934 4.09256 21.8412L8.19141 20.3041C8.72605 20.1036 9.21158 19.791 9.61534 19.3872L10.0024 19L5.00244 14L4.61534 14.3872C4.21158 14.791 3.89894 15.2765 3.69845 15.8112Z" fill="#EB5757"/>
<path opacity="0.25" d="M5 14L10 19L19.5 9.5L14.5 4.5L5 14Z" fill="#EB5757"/>
<path d="M20.8787 8.12087L19.5 9.49951L14.5 4.49951L15.8787 3.12087C17.0503 1.94929 18.9497 1.9493 20.1213 3.12087L20.8787 3.87823C22.0503 5.0498 22.0503 6.9493 20.8787 8.12087Z" fill="#EB5757"/>
</svg>
 <textarea className='normal-tag' placeholder='Write Note Here '  style={{height:100,width:300,padding:'0.5rem'}} onChange={handleNotes}  />

    </div>

    </div>
    <div >
      <h2 style={{padding:'1rem 0'}}>Terms & condition </h2>
      <p className='grey-text'>Whether you call it a terms of use, terms of service, or terms and conditions, this powerhouse document helps maintain control over your site as long as your guidelines fall within applicable laws.

Here are a few examples of what you can include in yours:
<br/>
<br/>
1. Establish and clarify your intellectual property rights<br/>
2. Limit your liabilities<br/>
3. Outline your dispute resolution options<br/>
4. Disclose your governing laws<br/>
5. Establish payment terms<br/>
6. Include shipping policy and return and refund details<br/>
7. Inform users about your privacy policy<br/>
8.Outline acceptable uses, prohibited behaviors, and their consequences<br/>
It answers several common customer service questions and provides clear protocols if users try to take advantage of your operations.</p>
    </div>

</div>

<div className={styles["right"]}>

<OrderSummary/>
<div className={`${styles["checkout-wrapper"]}`} style={{justifyContent:'flex-end',margin:'2rem 0'}}>
     <Button title="Confirm" onClick={ BookingDetails?.type=="shop" ? createBooking:createEventBooking} />
     </div>
</div>

     </div>
     
    </>
  )
}

export default Checkout