import Head from 'next/head'
import React from 'react'
import HomeNavbar from '@/component/Home/Navbar/Navbar'
import styles from '../styles/event.module.scss'
import Sidebar from '@/component/Event/Sidebar/Sidebar'
import EventCard from '@/component/Event/Eventcard/EventCard'
import { getAllEvent } from '@/services/eventService'

const event = ({eventArr}:any) => {
 
  
  return (
    <>
        <Head>
        <title>event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <HomeNavbar/>
     <div className={styles['event-wrapper']}>
        <Sidebar />
        <div className={styles["event-listing"]}>
          {eventArr?.map((event:any)=>{

            return  <EventCard key={event?._id} eventData={event} />
          })}


        </div>
     </div>
     </>
  )
}

export default event

export const getServerSideProps: any = async (context: any) => {

  const event:any = await getAllEvent("652d31286731fb324143cd41")

  return {
    props: {
     
      eventArr: event?.data?.result
      
    },
  };
};