import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.scss'
import HomeNavbar from '@/component/Home/Navbar/Navbar'
import Banner from '@/component/Home/Banner/Banner'
import Slider from '@/component/Home/Slider/Slider'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import DiscoverNow from '@/component/Home/DiscoverNow/DiscoverNow'
import ShopListing from '@/component/Home/ShopListing/ShopListing'
import ShopDetails from '@/component/ShopDetails/ShopDetails'
import { getShop, getShopById } from '@/services/userService'
import { getAllEvent } from '@/services/eventService'




export default function Home({ShopData,eventArr}:any) {


  var discover1={
    title:"CATEGORY" ,
    desc:"Discover all the new products and design furniture presented at the Salone del Mobile 2022.",
    sub_green:"DEO SALOON",
    sub_text:"2023"
  }
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <HomeNavbar/>
     <Banner ShopData={ShopData}/>
     {/* <DiscoverNow content={discover1} /> */}
     
     <ShopDetails ShopData={ShopData}/>
     <Slider sliderArr={eventArr}/>
    
     {/* <ShopListing /> */}
     
    </>

  
  )
}
// rendering using SSR for faster loading
export const getServerSideProps: any = async (context: any) => {
  const shop:any = await getShopById("652d31286731fb324143cd41");
  const event:any = await getAllEvent("652d31286731fb324143cd41")

  return {
    props: {
      ShopData: shop?.response|| [],
      eventArr: event?.data?.result
      
    },
  };
};
